GRAMMAR_POINTS = [
{"id": "G001", "title": "ang/si topic marker", "note": "Marks the topic of the sentence: ang/ang mga for common nouns; si/sina for names."},
{"id": "G002", "title": "ng/ni object-possessor", "note": "Marks direct object or possessor: ng for common nouns; ni/nina for names."},
{"id": "G003", "title": "sa/kay location-recipient", "note": "Marks location, direction, or recipient: sa for places/things; kay/kina for persons."},
{"id": "G004", "title": "plural marker mga", "note": "mga makes a noun plural (no change to the noun itself)."},
{"id": "G005", "title": "linker -ng/na", "note": "Links modifiers to nouns or verbs; use -ng after vowels, na after consonants."},
{"id": "G006", "title": "adjective + linker before noun", "note": "Place the adjective before the noun with a linker (e.g., malaking bahay)."},
{"id": "G007", "title": "noun + ng + noun (of)", "note": "Use ng to mark a possessor or whole-of relation (libro ng guro)."},
{"id": "G008", "title": "demonstratives ito/iyan/iyon", "note": "ito near speaker, iyan near listener, iyon far from both; pair with ang/si as needed."},
{"id": "G009", "title": "locatives dito/diyan/doon", "note": "dito here, diyan there near listener, doon there far; can stand alone or take sa."},
{"id": "G010", "title": "existential may", "note": "may + noun states existence or possession; often followed by a pronoun later in the clause."},
{"id": "G011", "title": "mayroon/meron forms", "note": "Mayroon/meron are fuller forms of may, often before pronouns or when stressed."},
{"id": "G012", "title": "negation hindi", "note": "Negates verbs, adjectives, and equational sentences; place before the word it negates."},
{"id": "G013", "title": "negation wala", "note": "Negates existence or possession; wala + noun or wala + sa + place."},
{"id": "G014", "title": "yes-no particle ba", "note": "Add ba after the first element to form a neutral yes-no question."},
{"id": "G015", "title": "tag question di ba", "note": "di ba adds a confirming tag like right; often at the end of a statement."},
{"id": "G016", "title": "question word ano", "note": "ano asks what; can link with ang markers or the linker when modifying a noun."},
{"id": "G017", "title": "question word sino", "note": "sino asks who; use kanino for whose or to whom."},
{"id": "G018", "title": "question word saan", "note": "saan asks where; use nasaan for where is someone or something."},
{"id": "G019", "title": "question word kailan", "note": "kailan asks when; can combine with noong, sa, or ngayong for clarity."},
{"id": "G020", "title": "question word bakit", "note": "bakit asks why; answer with kasi or dahil."},
{"id": "G021", "title": "question word paano", "note": "paano asks how; can take a linker when modifying a verb phrase."},
{"id": "G022", "title": "question word alin", "note": "alin asks which; plural forms alin-alin or alin sa mga."},
{"id": "G023", "title": "ilan vs ilang", "note": "ilan asks how many; ilang + noun means how many of that noun."},
{"id": "G024", "title": "magkano price", "note": "magkano asks price; magkano ito or magkano ang + item."},
{"id": "G025", "title": "gaano + adjective", "note": "gaano asks degree; gaano kabilis, gaano kalaki with ka- + adj."},
{"id": "G026", "title": "comparison mas + kaysa/sa", "note": "mas + adjective makes comparative; use kaysa or sa for than."},
{"id": "G027", "title": "superlative pinaka-", "note": "pinaka- + adjective forms the superlative (the most)."},
{"id": "G028", "title": "intensifier talagang", "note": "talagang intensifies a statement like really; often before the verb or adjective."},
{"id": "G029", "title": "softener medyo", "note": "medyo means somewhat or kind of; softens adjectives and verbs."},
{"id": "G030", "title": "masyado/masyadong (too)", "note": "masyado or masyadong marks excess; masyadong before adjectives or verbs."},
{"id": "G031", "title": "only lang", "note": "lang limits the scope to only or just; often after the focused word."},
{"id": "G032", "title": "contrast naman", "note": "naman adds contrast, politeness, or topic shift; softens requests and comparisons."},
{"id": "G033", "title": "particle na (already/now)", "note": "na means already, now, or change of state; places after the first element."},
{"id": "G034", "title": "still pa", "note": "pa means still or yet; combines with negatives for not yet (hindi pa)."},
{"id": "G035", "title": "also rin/din", "note": "rin/din mean also; choose rin after vowels or n, din after other consonants."},
{"id": "G036", "title": "hearsay daw/raw", "note": "daw/raw mark reported speech; use raw after vowels or n, daw after other consonants."},
{"id": "G037", "title": "maybe yata", "note": "yata softens with uncertainty or guess; usually after the first element."},
{"id": "G038", "title": "surprise pala", "note": "pala marks new or surprising info just realized by the speaker."},
{"id": "G039", "title": "politeness po/ho", "note": "po and ho add politeness; place after the first element or before the verb."},
{"id": "G040", "title": "emphasis nga", "note": "nga confirms or emphasizes something previously stated or implied."},
{"id": "G041", "title": "conjunction at (and)", "note": "Connects words or clauses; optional comma before at in long lists."},
{"id": "G042", "title": "but pero", "note": "pero introduces contrast or exception between clauses."},
{"id": "G043", "title": "because kasi", "note": "kasi gives a reason; often placed mid or end clause in casual speech."},
{"id": "G044", "title": "therefore kaya", "note": "kaya means so or therefore; links cause to result."},
{"id": "G045", "title": "even though kahit", "note": "kahit introduces concession; kahit + noun or kahit + clause."},
{"id": "G046", "title": "if kung", "note": "kung starts a condition; main clause can come before or after."},
{"id": "G047", "title": "para sa/kay (for someone)", "note": "para sa for things or groups; para kay/kina for specific people."},
{"id": "G048", "title": "para + infinitive (in order to)", "note": "para + makapag/maka/mag or ma marks purpose."},
{"id": "G049", "title": "mula…hanggang (from…to…)", "note": "Marks ranges of time or place; use hanggang sa before a place."},
{"id": "G050", "title": "bago/pagkatapos + verb", "note": "Use bago or pagkatapos bago mag or um form to say before or after doing."},
{"id": "G051", "title": "enclitic pronouns ko/mo/niya etc.", "note": "Short pronouns follow verbs or nouns to mark possession or actor (ko, mo, niya, namin, natin, ninyo, nila)."},
{"id": "G052", "title": "full possessives akin/iyo/kanya", "note": "akin, iyo, kanya, amin, atin, inyo, kanila stand alone or follow sa/para sa."},
{"id": "G053", "title": "natin vs namin", "note": "natin includes the listener; namin excludes the listener."},
{"id": "G054", "title": "kami vs tayo", "note": "kami excludes the listener; tayo includes the listener."},
{"id": "G055", "title": "linker with numbers", "note": "Numbers before nouns take a linker (tatlong libro, limang tao)."},
{"id": "G056", "title": "ordinal ika- + number", "note": "ika- forms ordinals (ika-3, ikalima); often with na for dates."},
{"id": "G057", "title": "noong + past time", "note": "noong marks past time points or periods (noong Lunes, noong bata ako)."},
{"id": "G058", "title": "sa + future time", "note": "sa marks scheduled or future time (sa Lunes, sa susunod na linggo)."},
{"id": "G059", "title": "tuwing + habitual time", "note": "tuwing means every or whenever; pairs with days or times."},
{"id": "G060", "title": "um- actor focus", "note": "um- marks actor-focused verbs; aspects use reduplication for ongoing and no redup for future."},
{"id": "G061", "title": "mag- actor focus", "note": "mag- future/infinitive; nag- completed; nag + redup imperfective for many activities."},
{"id": "G062", "title": "-in patient focus", "note": "-in targets the object; infix in- for completed, redup for ongoing, suffix -in in forms."},
{"id": "G063", "title": "i- object focus", "note": "i- highlights the thing moved, given, or used; completed often with in inserted (ibinigay)."},
{"id": "G064", "title": "-an locative-benefactive", "note": "-an focuses on place or recipient; completed often with in + -an (sinulatan)."},
{"id": "G065", "title": "ma- stative/involuntary", "note": "ma- describes states or unintentional actions (maganda, mahulog, makalimot)."},
{"id": "G066", "title": "maka- ability", "note": "maka- means manage to or be able to due to circumstance, not skill."},
{"id": "G067", "title": "makapag- ability to do activity", "note": "makapag- expresses ability to perform a mag- type activity (makapag-aral)."},
{"id": "G068", "title": "magpa- causative", "note": "magpa- means to have someone do something (magpagawa, magpaluto)."},
{"id": "G069", "title": "ipa- causative patient focus", "note": "ipa- focuses the thing caused to be done (ipagawa, ipaluto)."},
{"id": "G070", "title": "paki- polite request", "note": "paki- makes polite requests (pakibukas, pakipasa) often with po."},
{"id": "G071", "title": "naka- resultant state", "note": "naka- shows a state like wearing or positioned (nakasuot, nakaupo)."},
{"id": "G072", "title": "kaka- just did", "note": "kaka- + reduplicated first syllable means just did recently (kakakain)."},
{"id": "G073", "title": "CV reduplication for aspect", "note": "Copy the first CV of the root to mark ongoing or contemplated aspect."},
{"id": "G074", "title": "pa lang (just now/only just)", "note": "pa lang means just now or only just; often with completed or stative verbs."},
{"id": "G075", "title": "relative clause linker na", "note": "Use na between a noun and a clause that describes it (taong nakatira dito)."},
{"id": "G076", "title": "topic fronting with ay", "note": "ay inverts for emphasis or formal style: Topic ay Comment."},
{"id": "G077", "title": "not yet hindi pa", "note": "hindi pa means not yet; pa signals the action is still pending."},
{"id": "G078", "title": "permission puwede", "note": "puwede expresses permission or possibility; puwede + pronoun + mag/um verb."},
{"id": "G079", "title": "obligation kailangan", "note": "kailangan expresses need or obligation; kailangan + mag/um or kailangan ng + noun."},
{"id": "G080", "title": "gusto + verb clause", "note": "gusto + enclitic pronoun + linker + verb means want to do (gusto kong magbasa)."}
]
